### ISSUE TITLE
Error message running streamlit-folium... AttributeError: module 'click' has no attribute 'get_os_args'

### ISSUE THREAD

**Issue by richlysakowski** [randyzwitch/streamlit-folium#113]
Windows 10 
I get an error message:   Error message after installing streamlit-folium... AttributeError: module 'click' has no attribute 'get_os_args'

I start the application from the "Examples" directory with the command: 

>>> streamlit run streamlit_app.py

streamlit_folium_RandyZwitch\examples>streamlit run streamlit_app.py

My environment is called "metview_vapor"
(metview_vapor) C:\Users\PowerUser\Desktop\Geospatial_maps\streamlit_folium_RandyZwitch\examples>streamlit run streamlit_app.py
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\metview_vapor\Scripts\streamlit-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\ProgramData\Anaconda3\envs\metview_vapor\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\metview_vapor\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\envs\metview_vapor\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\envs\metview_vapor\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\envs\metview_vapor\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\metview_vapor\lib\site-packages\streamlit\cli.py", line 204, in main_run
    _main_run(target, args, flag_options=kwargs)
  File "C:\ProgramData\Anaconda3\envs\metview_vapor\lib\site-packages\streamlit\cli.py", line 232, in _main_run
    command_line = _get_command_line_as_string()
  File "C:\ProgramData\Anaconda3\envs\metview_vapor\lib\site-packages\streamlit\cli.py", line 221, in _get_command_line_as_string
    cmd_line_as_list.extend(click.get_os_args())
AttributeError: module 'click' has no attribute 'get_os_args'

Here is my environment:  

`conda list
# packages in environment at C:\ProgramData\Anaconda3\envs\metview_vapor:
#
# Name                    Version                   Build  Channel
affine                    2.3.1              pyhd8ed1ab_0    conda-forge
altair                    4.2.0              pyhd8ed1ab_1    conda-forge
anyio                     3.6.2              pyhd8ed1ab_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0          py310h8d17308_3    conda-forge
arrow-cpp                 10.0.1           h9c18f36_3_cpu    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
asttokens                 2.0.8              pyhd8ed1ab_0    conda-forge
attrs                     22.1.0             pyh71513ae_1    conda-forge
aws-c-auth                0.6.21               h1ba0662_1    conda-forge
aws-c-cal                 0.5.20               h4b5e85a_3    conda-forge
aws-c-common              0.8.5                hcfcfb64_0    conda-forge
aws-c-compression         0.2.16               h3dc32ea_0    conda-forge
aws-c-event-stream        0.2.16               hb67f86a_0    conda-forge
aws-c-http                0.6.29               h844ee93_0    conda-forge
aws-c-io                  0.13.11              hea55e33_2    conda-forge
aws-c-mqtt                0.7.13              h461ce70_10    conda-forge
aws-c-s3                  0.2.1                h0f2ed3e_2    conda-forge
aws-c-sdkutils            0.1.7                h3dc32ea_0    conda-forge
aws-checksums             0.1.14               h3dc32ea_0    conda-forge
aws-crt-cpp               0.18.16              h09df7fd_5    conda-forge
aws-sdk-cpp               1.9.379              h4d30238_6    conda-forge
babel                     2.10.3             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
base58                    2.1.1              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.11.1             pyha770c72_0    conda-forge
bleach                    5.0.1              pyhd8ed1ab_0    conda-forge
blinker                   1.5                pyhd8ed1ab_0    conda-forge
blosc                     1.21.1               h74325e0_3    conda-forge
bokeh                     2.4.3              pyhd8ed1ab_3    conda-forge
boltons                   21.0.0             pyhd8ed1ab_0    conda-forge
boost-cpp                 1.78.0               h9f4b32c_1    conda-forge
boto3                     1.26.45            pyhd8ed1ab_0    conda-forge
botocore                  1.29.45            pyhd8ed1ab_0    conda-forge
bottleneck                1.3.5           py310h9b08ddd_1    conda-forge
bqplot                    0.12.36            pyhd8ed1ab_0    conda-forge
branca                    0.6.0              pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                hcfcfb64_8    conda-forge
brotli-bin                1.0.9                hcfcfb64_8    conda-forge
brotli-python             1.0.9           py310h00ffb61_8    conda-forge
brotlipy                  0.7.0           py310h8d17308_1005    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-ares                    1.18.1               h8ffe710_0    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cachetools                5.2.0              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            hd694305_1014    conda-forge
cartopy                   0.21.0          py310h05326cb_1    conda-forge
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h628cb3f_2    conda-forge
cfgrib                    0.9.10.2           pyhd8ed1ab_0    conda-forge
cfitsio                   4.1.0                h5a969a9_0    conda-forge
cftime                    1.6.2           py310h9b08ddd_1    conda-forge
charset-normalizer        2.1.1              pyhd8ed1ab_0    conda-forge
click                     8.1.3           win_pyhd8ed1ab_2    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cloudpickle               2.2.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
colorcet                  3.0.1              pyhd8ed1ab_0    conda-forge
colour                    0.1.5                      py_0    conda-forge
conda                     22.9.0          py310h5588dad_2    conda-forge
conda-package-handling    1.9.0           py310h635b8f1_1    conda-forge
contextily                1.2.0              pyhd8ed1ab_0    conda-forge
contourpy                 1.0.5           py310h232114e_1    conda-forge
cryptography              38.0.2          py310h6e82f81_2    conda-forge
curl                      7.86.0               heaf79c2_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.0          py310h8d17308_1    conda-forge
dash                      2.7.1              pyhd8ed1ab_0    conda-forge
dash-bootstrap-components 1.3.0              pyhd8ed1ab_0    conda-forge
dash-core-components      2.0.0              pyhd8ed1ab_1    conda-forge
dash-daq                  0.5.0              pyh9f0ad1d_1    conda-forge
dash-html-components      2.0.0              pyhd8ed1ab_1    conda-forge
dash_colorscales          0.0.4              pyh9f0ad1d_0    conda-forge
dask                      2022.2.1           pyhd3eb1b0_0
dask-core                 2022.2.1           pyhd3eb1b0_0
datashader                0.14.2             pyh6c4a22f_0    conda-forge
datashape                 0.5.4                      py_1    conda-forge
debugpy                   1.6.3           py310h00ffb61_1    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
dill                      0.3.6              pyhd8ed1ab_1    conda-forge
distributed               2022.2.1           pyhd3eb1b0_0
dtale                     2.9.1              pyhd8ed1ab_0    conda-forge
eccodes                   2.27.0               hc5f4f04_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
executing                 1.1.1              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                h1537add_0    conda-forge
filelock                  3.9.0              pyhd8ed1ab_0    conda-forge
findlibs                  0.0.2              pyhd8ed1ab_0    conda-forge
fiona                     1.8.22          py310h4a685fe_5    conda-forge
flask                     2.2.2              pyhd8ed1ab_0    conda-forge
flask-compress            1.13               pyhd8ed1ab_0    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
folium                    0.14.0             pyhd8ed1ab_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.1               hbde0cde_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0          py310h8d17308_1    conda-forge
freeglut                  3.2.2                h0e60522_1    conda-forge
freetype                  2.12.1               h546665d_0    conda-forge
freexl                    1.0.6                h67ca5e6_1    conda-forge
fsspec                    2022.10.0          pyhd8ed1ab_0    conda-forge
future                    0.18.2             pyhd8ed1ab_6    conda-forge
gdal                      3.6.0           py310he15e4ab_1    conda-forge
gdown                     4.6.0              pyhd8ed1ab_0    conda-forge
geographiclib             1.52               pyhd8ed1ab_0    conda-forge
geojson                   2.5.0                      py_0    conda-forge
geopandas                 0.9.0              pyhd8ed1ab_0    conda-forge
geopandas-base            0.12.1             pyha770c72_1    conda-forge
geopy                     2.3.0              pyhd8ed1ab_0    conda-forge
geos                      3.11.0               h39d44d4_0    conda-forge
geotiff                   1.7.1                h4ffd875_4    conda-forge
geoviews                  1.9.5              pyhd8ed1ab_0    conda-forge
geoviews-core             1.9.5              pyha770c72_0    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
gflags                    2.2.2             ha925a31_1004    conda-forge
gitdb                     4.0.10             pyhd8ed1ab_0    conda-forge
gitpython                 3.1.30             pyhd8ed1ab_0    conda-forge
glog                      0.6.0                h4797de2_0    conda-forge
gmaps                     0.9.0                      py_0    conda-forge
hdf4                      4.2.15               h0e5069d_4    conda-forge
hdf5                      1.12.2          nompi_h57737ce_100    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
holoviews                 1.15.2             pyhd8ed1ab_0    conda-forge
icu                       70.1                 h0e60522_0    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
importlib-metadata        5.0.0              pyha770c72_1    conda-forge
importlib_resources       5.10.0             pyhd8ed1ab_0    conda-forge
intel-openmp              2022.1.0          h57928b3_3787    conda-forge
ipyevents                 2.0.1              pyhd8ed1ab_0    conda-forge
ipyfilechooser            0.6.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.16.2             pyh025b116_0    conda-forge
ipyleaflet                0.17.2             pyhd8ed1ab_0    conda-forge
ipysheet                  0.7.0              pyhd8ed1ab_0    conda-forge
ipython                   8.5.0              pyh08f2357_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipytree                   0.2.2              pyhd8ed1ab_0    conda-forge
ipywidgets                7.7.2              pyhd8ed1ab_0    conda-forge
isodate                   0.6.1                    pypi_0    pypi
itsdangerous              2.1.2              pyhd8ed1ab_0    conda-forge
jasper                    2.0.33               h77af90b_0    conda-forge
jedi                      0.18.1             pyhd8ed1ab_2    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jmespath                  1.0.1              pyhd8ed1ab_0    conda-forge
joblib                    1.2.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h8ffe710_2    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                4.16.0             pyhd8ed1ab_0    conda-forge
jupyter_client            7.4.4              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1          py310h5588dad_1    conda-forge
jupyter_server            1.21.0             pyhd8ed1ab_0    conda-forge
jupyterlab                3.5.2              pyhd8ed1ab_0    conda-forge
jupyterlab_execute_time   2.3.1              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.16.1             pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        1.1.1              pyhd8ed1ab_0    conda-forge
kealib                    1.4.15               hdf81f3a_1    conda-forge
keplergl                  0.3.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.4           py310h232114e_1    conda-forge
krb5                      1.19.3               hc8ab02b_0    conda-forge
lcms2                     2.14                 h90d422f_0    conda-forge
leafmap                   0.15.0             pyhd8ed1ab_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libabseil                 20220623.0      cxx17_h1a56200_6    conda-forge
libaec                    1.0.6                h39d44d4_0    conda-forge
libarrow                  10.0.1           h226723c_3_cpu    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libbrotlicommon           1.0.9                hcfcfb64_8    conda-forge
libbrotlidec              1.0.9                hcfcfb64_8    conda-forge
libbrotlienc              1.0.9                hcfcfb64_8    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libcrc32c                 1.1.2                h0e60522_0    conda-forge
libcurl                   7.86.0               heaf79c2_0    conda-forge
libdeflate                1.14                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libgdal                   3.6.0                hc5f2fbc_1    conda-forge
libglib                   2.74.1               he8f3873_1    conda-forge
libgoogle-cloud           2.5.0                h5fc25aa_1    conda-forge
libgrpc                   1.51.1               h6a6baca_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
libkml                    1.3.0             hf2ab4e4_1015    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h85765be_104    conda-forge
libpng                    1.6.38               h19919ed_0    conda-forge
libpq                     14.5                 hf15792c_2    conda-forge
libprotobuf               3.21.12              h12be248_0    conda-forge
librttopo                 1.1.0               h2842628_11    conda-forge
libsodium                 1.0.18               h8d14728_1    conda-forge
libspatialindex           1.9.3                h39d44d4_4    conda-forge
libspatialite             5.0.1               hd560d62_21    conda-forge
libsqlite                 3.39.4               hcfcfb64_0    conda-forge
libssh2                   1.10.0               h9a1e1f7_3    conda-forge
libthrift                 0.16.0               h9ce19ad_2    conda-forge
libtiff                   4.4.0                h8e97e67_4    conda-forge
libutf8proc               2.8.0                h82a8f57_0    conda-forge
libwebp-base              1.2.4                h8ffe710_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.10.3               hc3477c8_0    conda-forge
libzip                    1.9.2                h519de47_1    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
llvmlite                  0.39.1          py310hb84602e_1    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lxml                      4.9.2                    pypi_0    pypi
lz4                       4.2.0           py310hbbb2075_0    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markdown                  3.4.1              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1           py310h8d17308_2    conda-forge
matplotlib-base           3.6.1           py310h51140c5_1    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
menuinst                  1.4.19          py310h5588dad_1    conda-forge
mercantile                1.2.1              pyhd8ed1ab_0    conda-forge
metpy                     1.3.1              pyhd8ed1ab_0    conda-forge
metview-python            1.13.0             pyhd8ed1ab_0    conda-forge
missingno                 0.4.2                      py_1    conda-forge
mistune                   2.0.4              pyhd8ed1ab_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
msgpack-python            1.0.4           py310h232114e_1    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
multipledispatch          0.6.0                      py_0    conda-forge
multiprocess              0.70.14         py310h8d17308_3    conda-forge
munch                     2.5.0                      py_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclassic                 0.4.5              pyhd8ed1ab_0    conda-forge
nbclient                  0.7.0              pyhd8ed1ab_0    conda-forge
nbconvert                 7.2.3              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.2.3              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.2.3              pyhd8ed1ab_0    conda-forge
nbformat                  5.7.0              pyhd8ed1ab_0    conda-forge
nest-asyncio              1.5.6              pyhd8ed1ab_0    conda-forge
netcdf4                   1.6.1           nompi_py310h459bb5f_101    conda-forge
networkx                  2.8.8              pyhd8ed1ab_0    conda-forge
noaa-coops                0.1.9                    pypi_0    pypi
noaa-sdk                  0.1.21                   pypi_0    pypi
notebook                  6.5.1              pyha770c72_0    conda-forge
notebook-shim             0.2.0              pyhd8ed1ab_0    conda-forge
numba                     0.56.3          py310h19bcfe9_0    conda-forge
numpy                     1.23.4          py310h4a8f9c9_1    conda-forge
nwsapy                    1.0.3                    pypi_0    pypi
openjpeg                  2.5.0                hc9384bd_1    conda-forge
openpyxl                  3.0.10          py310h8d17308_2    conda-forge
openssl                   3.0.7                hcfcfb64_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.5.3           py310h1c4a608_0    conda-forge
pandoc                    2.19.2               h57928b3_1    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
panel                     0.14.1             pyhd8ed1ab_0    conda-forge
param                     1.12.2             pyh6c4a22f_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.3.0              pyhd8ed1ab_0    conda-forge
pathos                    0.3.0              pyhd8ed1ab_0    conda-forge
patsy                     0.5.3              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0           py310hd4fb230_3    conda-forge
pint                      0.20.1             pyhd8ed1ab_0    conda-forge
pip                       22.3               pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              2.6.2                    pypi_0    pypi
plotly                    5.9.0           py310haa95532_0
pooch                     1.6.0              pyhd8ed1ab_0    conda-forge
poppler                   22.11.0              ha6c1112_0    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                14.5                 h58a5ca5_2    conda-forge
pox                       0.3.2              pyhd8ed1ab_0    conda-forge
ppft                      1.7.6.6            pyhd8ed1ab_0    conda-forge
proj                      9.1.0                h3863b3b_0    conda-forge
prometheus_client         0.15.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.31             pyha770c72_0    conda-forge
protobuf                  4.21.12         py310h00ffb61_0    conda-forge
pscript                   0.7.7              pyhd8ed1ab_0    conda-forge
psutil                    5.9.3           py310h8d17308_1    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pyarrow                   10.0.1          py310hf00d861_3_cpu    conda-forge
pycosat                   0.6.4           py310h8d17308_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycrs                     1.0.2                      py_0    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pydeck                    0.8.0              pyhd8ed1ab_0    conda-forge
pygments                  2.13.0             pyhd8ed1ab_0    conda-forge
pympler                   1.0.1              pyhd8ed1ab_0    conda-forge
pyopenssl                 22.1.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.9              pyhd8ed1ab_0    conda-forge
pyproj                    3.4.0           py310h0e9dbc5_2    conda-forge
pyrsistent                0.18.1          py310h8d17308_2    conda-forge
pyshp                     2.3.1              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1              pyh0701188_6    conda-forge
pystac                    1.6.1              pyhd8ed1ab_1    conda-forge
pystac-client             0.5.1              pyhd8ed1ab_0    conda-forge
python                    3.10.6          hcf16a7b_0_cpython    conda-forge
python-awips              18.1.11            pyhd8ed1ab_0    conda-forge
python-box                6.1.0           py310h8d17308_0    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-eccodes            1.4.2           py310h2873277_0    conda-forge
python-fastjsonschema     2.16.2             pyhd8ed1ab_0    conda-forge
python-tzdata             2022.7             pyhd8ed1ab_0    conda-forge
python_abi                3.10                    2_cp310    conda-forge
pytz                      2022.5             pyhd8ed1ab_0    conda-forge
pytz-deprecation-shim     0.1.0.post0     py310h5588dad_3    conda-forge
pyviz_comms               2.2.1              pyhd8ed1ab_1    conda-forge
pywin32                   304             py310h00ffb61_2    conda-forge
pywinpty                  2.0.9           py310h00ffb61_0    conda-forge
pyyaml                    6.0             py310h8d17308_5    conda-forge
pyzmq                     24.0.1          py310hcd737a0_1    conda-forge
rasterio                  1.3.4           py310h1f46e14_0    conda-forge
re2                       2022.06.01           h0e60522_1    conda-forge
requests                  2.28.2             pyhd8ed1ab_0    conda-forge
requests-file             1.5.1                    pypi_0    pypi
requests-toolbelt         0.10.1                   pypi_0    pypi
rtree                     1.0.1           py310h1cbd46b_1    conda-forge
ruamel.yaml               0.17.21         py310h8d17308_2    conda-forge
ruamel.yaml.clib          0.2.7           py310h8d17308_1    conda-forge
ruamel_yaml               0.15.80         py310h8d17308_1008    conda-forge
s3transfer                0.6.0              pyhd8ed1ab_0    conda-forge
scikit-learn              1.2.0           py310had3394f_0    conda-forge
scipy                     1.9.3           py310h578b7cb_1    conda-forge
scooby                    0.7.0              pyhd8ed1ab_1    conda-forge
seaborn                   0.10.1                     py_0    conda-forge
semver                    2.13.0             pyh9f0ad1d_0    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                65.5.0             pyhd8ed1ab_0    conda-forge
shapely                   1.8.5           py310h3734685_1    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
snappy                    1.1.9                hfb803bf_2    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.39.4               hcfcfb64_0    conda-forge
squarify                  0.4.3                      py_0    conda-forge
stack_data                0.5.1              pyhd8ed1ab_0    conda-forge
statsmodels               0.13.5          py310h9b08ddd_2    conda-forge
streamlit                 1.8.0              pyhd8ed1ab_0    conda-forge
streamlit-folium          0.11.0             pyhd8ed1ab_0    conda-forge
strsimpy                  0.1.9              pyh9f0ad1d_0    conda-forge
tbb                       2021.6.0             h91493d7_1    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tenacity                  8.1.0              pyhd8ed1ab_0    conda-forge
terminado                 0.17.0             pyh08f2357_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tiledb                    2.11.3               h3132609_1    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
tornado                   6.2             py310h8d17308_1    conda-forge
tqdm                      4.64.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.5.0              pyhd8ed1ab_0    conda-forge
traittypes                0.2.1              pyh9f0ad1d_2    conda-forge
typing_extensions         4.4.0              pyha770c72_0    conda-forge
tzdata                    2022e                h191b570_0    conda-forge
tzlocal                   4.2             py310h5588dad_2    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodedata2              14.0.0          py310h8d17308_2    conda-forge
urllib3                   1.26.11            pyhd8ed1ab_0    conda-forge
validators                0.18.2             pyhd3deb0d_0    conda-forge
vc                        14.3                 h3d8a991_9    conda-forge
vs2015_runtime            14.32.31332          h1d6e394_9    conda-forge
watchdog                  2.2.1           py310h5588dad_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.4.1              pyhd8ed1ab_0    conda-forge
werkzeug                  2.2.2              pyhd8ed1ab_0    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
whitebox                  2.2.0              pyhd8ed1ab_0    conda-forge
whiteboxgui               2.2.0              pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.1              pyha770c72_0    conda-forge
win_inet_pton             1.1.0           py310h5588dad_5    conda-forge
winpty                    0.4.3                         4    conda-forge
xarray                    2022.10.0          pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.4                h63175ca_1    conda-forge
xlrd                      2.0.1              pyhd8ed1ab_3    conda-forge
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libx11               1.7.2                hcd874cb_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xyzservices               2022.9.0           pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
zeep                      4.2.1                    pypi_0    pypi
zeromq                    4.3.4                h0e60522_1    conda-forge
zict                      2.2.0              pyhd8ed1ab_0    conda-forge
zipp                      3.10.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hcfcfb64_4    conda-forge
zstd                      1.5.2                h7755175_4    conda-forge`

**Comment by blackary** [comment]
@richlysakowski Could you try upgrading to the latest version of streamlit-folium and see if this error goes away? It seems like it might be being caused by installing some older versions of dependencies
